name: Test for Dependabot Secrets
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Actions secrets
        env:
          ACTIONS_SECRETS: ${{ secrets.ACTIONS_SECRETS }}
          DEPENDABOT_SECRETS: ${{ secrets.DEPENDABOT_SECRETS }}
        shell: pwsh
        run: |
          $test1 = $(If ($env:ACTIONS_SECRETS -eq 'true') { 1 } Else { 0 })
          $test2 = $(If ($env:DEPENDABOT_SECRETS -eq 'true') { 1 } Else { 0 })
          
          echo "Actions Secrets = $test1"
          echo "Dependabot Secrets = $test2"
          
          
        
