name: Deploy
on:
  push:
    branches: main
    tags: '*'
env:
  DOTNET_NOLOGO: true
jobs:
  staging:
    runs-on: ubuntu-20.04
    steps:
      - name: Hi
        run: echo 'Hi'
  production:
    runs-on: ubuntu-20.04
    environment: production
    steps:
      - name: Hi
        run: echo 'Hi'
