name: Deploy
on:
  pull_request:
  push:
env:
  DOTNET_NOLOGO: true
jobs:
  staging:
    runs-on: windows-2019 # Because code signing https://github.com/NuGet/Home/issues/7939
    steps:
      - name: Get signing cert
        run: |
          [IO.File]::WriteAllBytes("signing-cert.pfx", [Convert]::FromBase64String("${{ secrets.NUGET_SIGNING_CERT_BASE64 }}"))
        shell: pwsh
      - name: Test
        run: |
          ls
          echo "Can I get the signing cert from a fork?"
          cat signing-cert.pfx
        shell: bash
